import 'package:flutter/material.dart';
import 'package:advanced_login_app/screens/department_model.dart';

class DepartmentData {
  static List<HospitalDepartment> getAllDepartments() {
    return [
      HospitalDepartment(
        id: 'gyn',
        name: 'Gynecology & Obstetrics',
        description: 'Women\'s health, pregnancy care, fertility treatments',
        iconCode: 'gynecology',
        primaryColor: const Color(0xFFE91E63),
        secondaryColor: const Color(0xFFF48FB1),
        specializations: ['Pregnancy Care', 'Fertility', 'Menopause', 'PCOS'],
        doctorCount: 18,
        avgRating: 4.8,
        imageAsset: 'assets/departments/gynecology.jpg',
        commonProcedures: ['Ultrasound', 'Pap Smear', 'IUD Insertion', 'HSG'],
        avgWaitTime: 25,
        telemedicineAvailable: true,
        emergencyService: true,
      ),
      HospitalDepartment(
        id: 'dent',
        name: 'Dentistry & Oral Surgery',
        description: 'Complete dental care, implants, orthodontics',
        iconCode: 'dentist',
        primaryColor: const Color(0xFF00BCD4),
        secondaryColor: const Color(0xFF80DEEA),
        specializations: ['Implants', 'Orthodontics', 'Cosmetic', 'Pediatric'],
        doctorCount: 12,
        avgRating: 4.7,
        imageAsset: 'assets/departments/dentistry.jpg',
        commonProcedures: ['Cleaning', 'Fillings', 'Root Canal', 'Braces'],
        avgWaitTime: 20,
        telemedicineAvailable: false,
        emergencyService: true,
      ),
      HospitalDepartment(
        id: 'psych',
        name: 'Psychology & Psychiatry',
        description: 'Mental health, therapy, counseling services',
        iconCode: 'psychology',
        primaryColor: const Color(0xFF9C27B0),
        secondaryColor: const Color(0xFFCE93D8),
        specializations: ['Clinical', 'Child', 'Addiction', 'Trauma'],
        doctorCount: 15,
        avgRating: 4.9,
        imageAsset: 'assets/departments/psychology.jpg',
        commonProcedures: ['Therapy', 'Counseling', 'Assessment', 'Medication'],
        avgWaitTime: 15,
        telemedicineAvailable: true,
        emergencyService: false,
      ),
      HospitalDepartment(
        id: 'cardio',
        name: 'Cardiology',
        description: 'Heart care, cardiovascular treatments',
        iconCode: 'cardiology',
        primaryColor: const Color(0xFFF44336),
        secondaryColor: const Color(0xFFEF9A9A),
        specializations: ['Interventional', 'Electrophysiology', 'Preventive'],
        doctorCount: 22,
        avgRating: 4.9,
        imageAsset: 'assets/departments/cardiology.jpg',
        commonProcedures: ['ECG', 'Echo', 'Angioplasty', 'Stress Test'],
        avgWaitTime: 30,
        telemedicineAvailable: true,
        emergencyService: true,
      ),
      HospitalDepartment(
        id: 'ortho',
        name: 'Orthopedics',
        description: 'Bone, joint, and muscle treatments',
        iconCode: 'orthopedics',
        primaryColor: const Color(0xFFFF9800),
        secondaryColor: const Color(0xFFFFCC80),
        specializations: ['Sports', 'Spine', 'Joint Replacement', 'Trauma'],
        doctorCount: 20,
        avgRating: 4.7,
        imageAsset: 'assets/departments/orthopedics.jpg',
        commonProcedures: ['X-Ray', 'MRI', 'Arthroscopy', 'Fracture Care'],
        avgWaitTime: 35,
        telemedicineAvailable: false,
        emergencyService: true,
      ),
      HospitalDepartment(
        id: 'ped',
        name: 'Pediatrics',
        description: 'Child healthcare from birth to adolescence',
        iconCode: 'pediatrics',
        primaryColor: const Color(0xFF2196F3),
        secondaryColor: const Color(0xFF90CAF9),
        specializations: ['Neonatal', 'Adolescent', 'Development', 'Allergy'],
        doctorCount: 25,
        avgRating: 4.8,
        imageAsset: 'assets/departments/pediatrics.jpg',
        commonProcedures: ['Vaccination', 'Growth Monitoring', 'Checkups'],
        avgWaitTime: 20,
        telemedicineAvailable: true,
        emergencyService: true,
      ),
      HospitalDepartment(
        id: 'neuro',
        name: 'Neurology',
        description: 'Brain and nervous system disorders',
        iconCode: 'neurology',
        primaryColor: const Color(0xFF673AB7),
        secondaryColor: const Color(0xFFB39DDB),
        specializations: ['Stroke', 'Epilepsy', 'Movement', 'Headache'],
        doctorCount: 16,
        avgRating: 4.8,
        imageAsset: 'assets/departments/neurology.jpg',
        commonProcedures: ['EEG', 'CT Scan', 'Nerve Conduction', 'EMG'],
        avgWaitTime: 40,
        telemedicineAvailable: true,
        emergencyService: true,
      ),
      HospitalDepartment(
        id: 'derm',
        name: 'Dermatology',
        description: 'Skin, hair, and nail conditions',
        iconCode: 'dermatology',
        primaryColor: const Color(0xFF4CAF50),
        secondaryColor: const Color(0xFFA5D6A7),
        specializations: ['Cosmetic', 'Surgical', 'Pediatric', 'Oncology'],
        doctorCount: 14,
        avgRating: 4.6,
        imageAsset: 'assets/departments/dermatology.jpg',
        commonProcedures: ['Biopsy', 'Laser', 'Acne Treatment', 'Skin Exam'],
        avgWaitTime: 30,
        telemedicineAvailable: true,
        emergencyService: false,
      ),
      HospitalDepartment(
        id: 'eye',
        name: 'Ophthalmology',
        description: 'Eye care and vision correction',
        iconCode: 'ophthalmology',
        primaryColor: const Color(0xFF03A9F4),
        secondaryColor: const Color(0xFF81D4FA),
        specializations: ['Cataract', 'Retina', 'Glaucoma', 'Cornea'],
        doctorCount: 12,
        avgRating: 4.7,
        imageAsset: 'assets/departments/ophthalmology.jpg',
        commonProcedures: ['Eye Exam', 'LASIK', 'Cataract Surgery', 'Laser'],
        avgWaitTime: 25,
        telemedicineAvailable: false,
        emergencyService: true,
      ),
      HospitalDepartment(
        id: 'ent',
        name: 'ENT (Ear, Nose, Throat)',
        description: 'Head and neck disorders',
        iconCode: 'ent',
        primaryColor: const Color(0xFF009688),
        secondaryColor: const Color(0xFF80CBC4),
        specializations: ['Audiology', 'Sinuses', 'Voice', 'Allergy'],
        doctorCount: 10,
        avgRating: 4.5,
        imageAsset: 'assets/departments/ent.jpg',
        commonProcedures: ['Endoscopy', 'Hearing Test', 'Tonsillectomy'],
        avgWaitTime: 20,
        telemedicineAvailable: true,
        emergencyService: true,
      ),
      HospitalDepartment(
        id: 'uro',
        name: 'Urology',
        description: 'Urinary system and male reproductive health',
        iconCode: 'urology',
        primaryColor: const Color(0xFF3F51B5),
        secondaryColor: const Color(0xFF9FA8DA),
        specializations: ['Oncology', 'Stone', 'Infertility', 'Pediatric'],
        doctorCount: 11,
        avgRating: 4.6,
        imageAsset: 'assets/departments/urology.jpg',
        commonProcedures: ['Ultrasound', 'Cystoscopy', 'Lithotripsy'],
        avgWaitTime: 35,
        telemedicineAvailable: true,
        emergencyService: true,
      ),
      HospitalDepartment(
        id: 'gastro',
        name: 'Gastroenterology',
        description: 'Digestive system disorders',
        iconCode: 'gastroenterology',
        primaryColor: const Color(0xFF8BC34A),
        secondaryColor: const Color(0xFFC5E1A5),
        specializations: ['Endoscopy', 'Liver', 'IBD', 'Nutrition'],
        doctorCount: 13,
        avgRating: 4.7,
        imageAsset: 'assets/departments/gastroenterology.jpg',
        commonProcedures: ['Colonoscopy', 'Endoscopy', 'Liver Biopsy'],
        avgWaitTime: 30,
        telemedicineAvailable: true,
        emergencyService: true,
      ),
      HospitalDepartment(
        id: 'onco',
        name: 'Oncology',
        description: 'Cancer diagnosis and treatment',
        iconCode: 'oncology',
        primaryColor: const Color(0xFF795548),
        secondaryColor: const Color(0xFFBCAAA4),
        specializations: ['Medical', 'Radiation', 'Surgical', 'Pediatric'],
        doctorCount: 18,
        avgRating: 4.9,
        imageAsset: 'assets/departments/oncology.jpg',
        commonProcedures: ['Chemotherapy', 'Radiation', 'Biopsy', 'Surgery'],
        avgWaitTime: 45,
        telemedicineAvailable: true,
        emergencyService: true,
      ),
      HospitalDepartment(
        id: 'endo',
        name: 'Endocrinology',
        description: 'Hormonal and metabolic disorders',
        iconCode: 'endocrinology',
        primaryColor: const Color(0xFFFF5722),
        secondaryColor: const Color(0xFFFFAB91),
        specializations: ['Diabetes', 'Thyroid', 'Metabolic', 'Obesity'],
        doctorCount: 9,
        avgRating: 4.6,
        imageAsset: 'assets/departments/endocrinology.jpg',
        commonProcedures: ['Hormone Tests', 'Thyroid Scan', 'Education'],
        avgWaitTime: 25,
        telemedicineAvailable: true,
        emergencyService: false,
      ),
      HospitalDepartment(
        id: 'nephro',
        name: 'Nephrology',
        description: 'Kidney diseases and dialysis',
        iconCode: 'nephrology',
        primaryColor: const Color(0xFF607D8B),
        secondaryColor: const Color(0xFFB0BEC5),
        specializations: ['Dialysis', 'Transplant', 'Hypertension'],
        doctorCount: 8,
        avgRating: 4.7,
        imageAsset: 'assets/departments/nephrology.jpg',
        commonProcedures: ['Dialysis', 'Biopsy', 'Ultrasound', 'Lab Tests'],
        avgWaitTime: 40,
        telemedicineAvailable: true,
        emergencyService: true,
      ),
      HospitalDepartment(
        id: 'pulmo',
        name: 'Pulmonology',
        description: 'Respiratory system and lung diseases',
        iconCode: 'pulmonology',
        primaryColor: const Color(0xFF00ACC1),
        secondaryColor: const Color(0xFF80DEEA),
        specializations: ['Asthma', 'COPD', 'Sleep', 'Critical Care'],
        doctorCount: 10,
        avgRating: 4.6,
        imageAsset: 'assets/departments/pulmonology.jpg',
        commonProcedures: ['Spirometry', 'Bronchoscopy', 'Sleep Study'],
        avgWaitTime: 30,
        telemedicineAvailable: true,
        emergencyService: true,
      ),
      HospitalDepartment(
        id: 'rheum',
        name: 'Rheumatology',
        description: 'Arthritis and autoimmune diseases',
        iconCode: 'rheumatology',
        primaryColor: const Color(0xFFAB47BC),
        secondaryColor: const Color(0xFFCE93D8),
        specializations: ['Arthritis', 'Lupus', 'Osteoporosis', 'Pain'],
        doctorCount: 7,
        avgRating: 4.5,
        imageAsset: 'assets/departments/rheumatology.jpg',
        commonProcedures: ['Joint Injection', 'Blood Tests', 'X-Rays'],
        avgWaitTime: 35,
        telemedicineAvailable: true,
        emergencyService: false,
      ),
      HospitalDepartment(
        id: 'hema',
        name: 'Hematology',
        description: 'Blood disorders and cancers',
        iconCode: 'hematology',
        primaryColor: const Color(0xFFD32F2F),
        secondaryColor: const Color(0xFFEF9A9A),
        specializations: ['Oncology', 'Coagulation', 'Transfusion', 'BMT'],
        doctorCount: 6,
        avgRating: 4.8,
        imageAsset: 'assets/departments/hematology.jpg',
        commonProcedures: ['Blood Tests', 'Bone Marrow', 'Transfusion'],
        avgWaitTime: 30,
        telemedicineAvailable: true,
        emergencyService: true,
      ),
      HospitalDepartment(
        id: 'radio',
        name: 'Radiology',
        description: 'Medical imaging and diagnostics',
        iconCode: 'radiology',
        primaryColor: const Color(0xFF455A64),
        secondaryColor: const Color(0xFF90A4AE),
        specializations: ['MRI', 'CT', 'Ultrasound', 'Interventional'],
        doctorCount: 15,
        avgRating: 4.7,
        imageAsset: 'assets/departments/radiology.jpg',
        commonProcedures: ['X-Ray', 'MRI', 'CT Scan', 'Ultrasound'],
        avgWaitTime: 15,
        telemedicineAvailable: false,
        emergencyService: true,
      ),
      HospitalDepartment(
        id: 'path',
        name: 'Pathology',
        description: 'Laboratory testing and diagnosis',
        iconCode: 'pathology',
        primaryColor: const Color(0xFF78909C),
        secondaryColor: const Color(0xFFB0BEC5),
        specializations: ['Clinical', 'Anatomical', 'Molecular', 'Cytology'],
        doctorCount: 12,
        avgRating: 4.6,
        imageAsset: 'assets/departments/pathology.jpg',
        commonProcedures: ['Biopsy', 'Blood Tests', 'Culture', 'Analysis'],
        avgWaitTime: 10,
        telemedicineAvailable: false,
        emergencyService: true,
      ),
      HospitalDepartment(
        id: 'gen',
        name: 'General Medicine',
        description: 'Primary care and comprehensive health',
        iconCode: 'general',
        primaryColor: const Color(0xFF6C63FF),
        secondaryColor: const Color(0xFFA5A2FF),
        specializations: ['Preventive', 'Chronic', 'Acute', 'Geriatric'],
        doctorCount: 30,
        avgRating: 4.5,
        imageAsset: 'assets/departments/general.jpg',
        commonProcedures: ['Checkups', 'Vaccinations', 'Basic Tests'],
        avgWaitTime: 20,
        telemedicineAvailable: true,
        emergencyService: true,
      ),
    ];
  }

  static List<String> getAllSpecializations() {
    final specializations = <String>{};
    for (var dept in getAllDepartments()) {
      specializations.addAll(dept.specializations);
    }
    return specializations.toList();
  }
}
